spring.application.name=aetheria-backend
spring.datasource.url=jdbc:postgresql://ep-steep-waterfall-ao9ew9sc-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VNzoOFIe3c0T
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
server.port=8081

